// <auto-generated />
namespace DimensaoTeste.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TaskList1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskList1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272234413_TaskList1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
